apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontvue
spec:
  selector:
      matchLabels:
        app: frontvue
  replicas: 1
  template:
    metadata:
      labels:
        app: frontvue
    spec:
      containers:
        - name: frontvue
          image: frontvue:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always